name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_dotenv: ^5.0.2
  http: ^1.0.0
  google_fonts: ^4.0.5
  jiffy: ^6.1.0
  loadmore: ^2.1.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.11
  connectivity_plus: ^4.0.1
flutter:
  uses-material-design: true
  assets:
  - assets/.env
  - assets/images/
