name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  provider: ^6.1.2
  skeletons: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_dotenv: ^5.0.2
  http: ^1.0.0
  google_fonts: ^4.0.5
  jiffy: ^6.1.0
  loadmore: ^2.1.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.11
  connectivity_plus: ^4.0.1
flutter:
  uses-material-design: true
  assets:
  - assets/.env
  - assets/images/

flutter_native_splash:
  color: "#FFFFFF"  # Background color
  image: assets/images/splash_logo.png  # Your splash screen image
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#FFFFFF"
